#pragma once

#include "types.h"

typedef struct {
    f32 x, y, z;
} Vec3f;

typedef struct {
    s16 x, y, z;
} Vec3s;

typedef struct {
    Vec3f pos;
    Vec3s rot;
} PosRot;

typedef enum SceneId {
    /* 0x00 */ SCENE_DEKU_TREE,
    /* 0x01 */ SCENE_DODONGOS_CAVERN,
    /* 0x02 */ SCENE_JABU_JABU,
    /* 0x03 */ SCENE_FOREST_TEMPLE,
    /* 0x04 */ SCENE_FIRE_TEMPLE,
    /* 0x05 */ SCENE_WATER_TEMPLE,
    /* 0x06 */ SCENE_SPIRIT_TEMPLE,
    /* 0x07 */ SCENE_SHADOW_TEMPLE,
    /* 0x08 */ SCENE_BOTTOM_OF_THE_WELL,
    /* 0x09 */ SCENE_ICE_CAVERN,
    /* 0x0A */ SCENE_GANONS_TOWER,
    /* 0x0B */ SCENE_GERUDO_TRAINING_GROUND,
    /* 0x0C */ SCENE_THIEVES_HIDEOUT,
    /* 0x0D */ SCENE_INSIDE_GANONS_CASTLE,
    /* 0x0E */ SCENE_GANONS_TOWER_COLLAPSE_INTERIOR,
    /* 0x0F */ SCENE_INSIDE_GANONS_CASTLE_COLLAPSE,
    /* 0x10 */ SCENE_TREASURE_BOX_SHOP,
    /* 0x11 */ SCENE_DEKU_TREE_BOSS,
    /* 0x12 */ SCENE_DODONGOS_CAVERN_BOSS,
    /* 0x13 */ SCENE_JABU_JABU_BOSS,
    /* 0x14 */ SCENE_FOREST_TEMPLE_BOSS,
    /* 0x15 */ SCENE_FIRE_TEMPLE_BOSS,
    /* 0x16 */ SCENE_WATER_TEMPLE_BOSS,
    /* 0x17 */ SCENE_SPIRIT_TEMPLE_BOSS,
    /* 0x18 */ SCENE_SHADOW_TEMPLE_BOSS,
    /* 0x19 */ SCENE_GANONDORF_BOSS,
    /* 0x1A */ SCENE_GANONS_TOWER_COLLAPSE_EXTERIOR,
    /* 0x1B */ SCENE_MARKET_ENTRANCE_DAY,
    /* 0x1C */ SCENE_MARKET_ENTRANCE_NIGHT,
    /* 0x1D */ SCENE_MARKET_ENTRANCE_RUINS,
    /* 0x1E */ SCENE_BACK_ALLEY_DAY,
    /* 0x1F */ SCENE_BACK_ALLEY_NIGHT,
    /* 0x20 */ SCENE_MARKET_DAY,
    /* 0x21 */ SCENE_MARKET_NIGHT,
    /* 0x22 */ SCENE_MARKET_RUINS,
    /* 0x23 */ SCENE_TEMPLE_OF_TIME_EXTERIOR_DAY,
    /* 0x24 */ SCENE_TEMPLE_OF_TIME_EXTERIOR_NIGHT,
    /* 0x25 */ SCENE_TEMPLE_OF_TIME_EXTERIOR_RUINS,
    /* 0x26 */ SCENE_KNOW_IT_ALL_BROS_HOUSE,
    /* 0x27 */ SCENE_TWINS_HOUSE,
    /* 0x28 */ SCENE_MIDOS_HOUSE,
    /* 0x29 */ SCENE_SARIAS_HOUSE,
    /* 0x2A */ SCENE_KAKARIKO_CENTER_GUEST_HOUSE,
    /* 0x2B */ SCENE_BACK_ALLEY_HOUSE,
    /* 0x2C */ SCENE_BAZAAR,
    /* 0x2D */ SCENE_KOKIRI_SHOP,
    /* 0x2E */ SCENE_GORON_SHOP,
    /* 0x2F */ SCENE_ZORA_SHOP,
    /* 0x30 */ SCENE_POTION_SHOP_KAKARIKO,
    /* 0x31 */ SCENE_POTION_SHOP_MARKET,
    /* 0x32 */ SCENE_BOMBCHU_SHOP,
    /* 0x33 */ SCENE_HAPPY_MASK_SHOP,
    /* 0x34 */ SCENE_LINKS_HOUSE,
    /* 0x35 */ SCENE_DOG_LADY_HOUSE,
    /* 0x36 */ SCENE_STABLE,
    /* 0x37 */ SCENE_IMPAS_HOUSE,
    /* 0x38 */ SCENE_LAKESIDE_LABORATORY,
    /* 0x39 */ SCENE_CARPENTERS_TENT,
    /* 0x3A */ SCENE_GRAVEKEEPERS_HUT,
    /* 0x3B */ SCENE_GREAT_FAIRYS_FOUNTAIN_MAGIC,
    /* 0x3C */ SCENE_FAIRYS_FOUNTAIN,
    /* 0x3D */ SCENE_GREAT_FAIRYS_FOUNTAIN_SPELLS,
    /* 0x3E */ SCENE_GROTTOS,
    /* 0x3F */ SCENE_REDEAD_GRAVE,
    /* 0x40 */ SCENE_GRAVE_WITH_FAIRYS_FOUNTAIN,
    /* 0x41 */ SCENE_ROYAL_FAMILYS_TOMB,
    /* 0x42 */ SCENE_SHOOTING_GALLERY,
    /* 0x43 */ SCENE_TEMPLE_OF_TIME,
    /* 0x44 */ SCENE_CHAMBER_OF_THE_SAGES,
    /* 0x45 */ SCENE_CASTLE_COURTYARD_GUARDS_DAY,
    /* 0x46 */ SCENE_CASTLE_COURTYARD_GUARDS_NIGHT,
    /* 0x47 */ SCENE_CUTSCENE_MAP,
    /* 0x48 */ SCENE_WINDMILL_AND_DAMPES_GRAVE,
    /* 0x49 */ SCENE_FISHING_POND,
    /* 0x4A */ SCENE_CASTLE_COURTYARD_ZELDA,
    /* 0x4B */ SCENE_BOMBCHU_BOWLING_ALLEY,
    /* 0x4C */ SCENE_LON_LON_BUILDINGS,
    /* 0x4D */ SCENE_MARKET_GUARD_HOUSE,
    /* 0x4E */ SCENE_POTION_SHOP_GRANNY,
    /* 0x4F */ SCENE_GANON_BOSS,
    /* 0x50 */ SCENE_HOUSE_OF_SKULLTULA,
    /* 0x51 */ SCENE_HYRULE_FIELD,
    /* 0x52 */ SCENE_KAKARIKO_VILLAGE,
    /* 0x53 */ SCENE_GRAVEYARD,
    /* 0x54 */ SCENE_ZORAS_RIVER,
    /* 0x55 */ SCENE_KOKIRI_FOREST,
    /* 0x56 */ SCENE_SACRED_FOREST_MEADOW,
    /* 0x57 */ SCENE_LAKE_HYLIA,
    /* 0x58 */ SCENE_ZORAS_DOMAIN,
    /* 0x59 */ SCENE_ZORAS_FOUNTAIN,
    /* 0x5A */ SCENE_GERUDO_VALLEY,
    /* 0x5B */ SCENE_LOST_WOODS,
    /* 0x5C */ SCENE_DESERT_COLOSSUS,
    /* 0x5D */ SCENE_GERUDOS_FORTRESS,
    /* 0x5E */ SCENE_HAUNTED_WASTELAND,
    /* 0x5F */ SCENE_HYRULE_CASTLE,
    /* 0x60 */ SCENE_DEATH_MOUNTAIN_TRAIL,
    /* 0x61 */ SCENE_DEATH_MOUNTAIN_CRATER,
    /* 0x62 */ SCENE_GORON_CITY,
    /* 0x63 */ SCENE_LON_LON_RANCH,
    /* 0x64 */ SCENE_OUTSIDE_GANONS_CASTLE,
    /* 0x65 */ SCENE_65,
    /* 0x66 */ SCENE_66,
    /* 0x67 */ SCENE_67,
    /* 0x68 */ SCENE_68,
    /* 0x69 */ SCENE_69,
    /* 0x6A */ SCENE_6A,
    /* 0x6B */ SCENE_HYRULE_FIELD_TITLE_SCREEN,
    /* 0x6C */ SCENE_MAX,
} SceneId;

typedef enum {
    /* 0x00 */ GI_INVALID, // Link picks up chest and it sends him flying upwards
    /* 0x01 */ GI_BOMBS_5,
    /* 0x02 */ GI_NUTS_5,
    /* 0x03 */ GI_BOMBCHUS_10,
    /* 0x04 */ GI_BOW,
    /* 0x05 */ GI_SLINGSHOT,
    /* 0x06 */ GI_BOOMERANG,
    /* 0x07 */ GI_STICKS_1,
    /* 0x08 */ GI_HOOKSHOT,
    /* 0x09 */ GI_LONGSHOT,
    /* 0x0A */ GI_LENS,
    /* 0x0B */ GI_LETTER_ZELDA,
    /* 0x0C */ GI_OCARINA_OOT,
    /* 0x0D */ GI_HAMMER,
    /* 0x0E */ GI_COJIRO,
    /* 0x0F */ GI_BOTTLE,
    /* 0x10 */ GI_POTION_RED,
    /* 0x11 */ GI_POTION_GREEN,
    /* 0x12 */ GI_POTION_BLUE,
    /* 0x13 */ GI_FAIRY,
    /* 0x14 */ GI_MILK_BOTTLE,
    /* 0x15 */ GI_LETTER_RUTO,
    /* 0x16 */ GI_BEAN,
    /* 0x17 */ GI_MASK_SKULL,
    /* 0x18 */ GI_MASK_SPOOKY,
    /* 0x19 */ GI_CHICKEN, // uses bean message ID
    /* 0x1A */ GI_MASK_KEATON,
    /* 0x1B */ GI_MASK_BUNNY,
    /* 0x1C */ GI_MASK_TRUTH,
    /* 0x1D */ GI_POCKET_EGG,
    /* 0x1E */ GI_POCKET_CUCCO, // uses bean message ID
    /* 0x1F */ GI_ODD_MUSHROOM,
    /* 0x20 */ GI_ODD_POTION,
    /* 0x21 */ GI_SAW,
    /* 0x22 */ GI_SWORD_BROKEN,
    /* 0x23 */ GI_PERSCRIPTION,
    /* 0x24 */ GI_FROG,
    /* 0x25 */ GI_EYEDROPS,
    /* 0x26 */ GI_CLAIM_CHECK,
    /* 0x27 */ GI_SWORD_KOKIRI,
    /* 0x28 */ GI_SWORD_KNIFE,
    /* 0x29 */ GI_SHIELD_DEKU,   // or blue rupee if you have the shield
    /* 0x2A */ GI_SHIELD_HYLIAN, // or blue rupee if you have the shield
    /* 0x2B */ GI_SHIELD_MIRROR,
    /* 0x2C */ GI_TUNIC_GORON, // or blue rupee if you have the tunic
    /* 0x2D */ GI_TUNIC_ZORA,  // or blue rupee if you have the tunic
    /* 0x2E */ GI_BOOTS_IRON,
    /* 0x2F */ GI_BOOTS_HOVER,
    /* 0x30 */ GI_QUIVER_40,
    /* 0x31 */ GI_QUIVER_50,
    /* 0x32 */ GI_BOMB_BAG_20,
    /* 0x33 */ GI_BOMB_BAG_30,
    /* 0x34 */ GI_BOMB_BAG_40,
    /* 0x35 */ GI_GAUNTLETS_SILVER,
    /* 0x36 */ GI_GAUNTLETS_GOLD,
    /* 0x37 */ GI_SCALE_SILVER,
    /* 0x38 */ GI_SCALE_GOLD,
    /* 0x39 */ GI_STONE_OF_AGONY,
    /* 0x3A */ GI_GERUDO_CARD,
    /* 0x3B */ GI_OCARINA_FAIRY, // uses Ocarina of Time message ID
    /* 0x3C */ GI_SEEDS_5,
    /* 0x3D */ GI_HEART_CONTAINER,
    /* 0x3E */ GI_HEART_PIECE,
    /* 0x3F */ GI_KEY_BOSS,
    /* 0x40 */ GI_COMPASS,
    /* 0x41 */ GI_MAP,
    /* 0x42 */ GI_KEY_SMALL,
    /* 0x43 */ GI_MAGIC_SMALL, // or blue rupee if not from a drop
    /* 0x44 */ GI_MAGIC_LARGE, // or blue rupee if not from a drop
    /* 0x45 */ GI_WALLET_ADULT,
    /* 0x46 */ GI_WALLET_GIANT,
    /* 0x47 */ GI_WEIRD_EGG,
    /* 0x48 */ GI_HEART,
    /* 0x49 */ GI_ARROWS_SMALL,  // amount changes depending on context
    /* 0x4A */ GI_ARROWS_MEDIUM, // amount changes depending on context
    /* 0x4B */ GI_ARROWS_LARGE,  // amount changes depending on context
    /* 0x4C */ GI_RUPEE_GREEN,
    /* 0x4D */ GI_RUPEE_BLUE,
    /* 0x4E */ GI_RUPEE_RED,
    /* 0x4F */ GI_HEART_CONTAINER_2,
    /* 0x50 */ GI_MILK,
    /* 0x51 */ GI_MASK_GORON,
    /* 0x52 */ GI_MASK_ZORA,
    /* 0x53 */ GI_MASK_GERUDO,
    /* 0x54 */ GI_BRACELET,
    /* 0x55 */ GI_RUPEE_PURPLE,
    /* 0x56 */ GI_RUPEE_GOLD,
    /* 0x57 */ GI_SWORD_BGS,
    /* 0x58 */ GI_ARROW_FIRE,
    /* 0x59 */ GI_ARROW_ICE,
    /* 0x5A */ GI_ARROW_LIGHT,
    /* 0x5B */ GI_SKULL_TOKEN,
    /* 0x5C */ GI_DINS_FIRE,
    /* 0x5D */ GI_FARORES_WIND,
    /* 0x5E */ GI_NAYRUS_LOVE,
    /* 0x5F */ GI_BULLET_BAG_30,
    /* 0x60 */ GI_BULLET_BAG_40,
    /* 0x61 */ GI_STICKS_5,
    /* 0x62 */ GI_STICKS_10,
    /* 0x63 */ GI_NUTS_5_2,
    /* 0x64 */ GI_NUTS_10,
    /* 0x65 */ GI_BOMBS_1,
    /* 0x66 */ GI_BOMBS_10,
    /* 0x67 */ GI_BOMBS_20,
    /* 0x68 */ GI_BOMBS_30,
    /* 0x69 */ GI_SEEDS_30,
    /* 0x6A */ GI_BOMBCHUS_5,
    /* 0x6B */ GI_BOMBCHUS_20,
    /* 0x6C */ GI_FISH,
    /* 0x6D */ GI_BUGS,
    /* 0x6E */ GI_BLUE_FIRE,
    /* 0x6F */ GI_POE,
    /* 0x70 */ GI_BIG_POE,
    /* 0x71 */ GI_DOOR_KEY,          // specific to chest minigame
    /* 0x72 */ GI_RUPEE_GREEN_LOSE,  // specific to chest minigame
    /* 0x73 */ GI_RUPEE_BLUE_LOSE,   // specific to chest minigame
    /* 0x74 */ GI_RUPEE_RED_LOSE,    // specific to chest minigame
    /* 0x75 */ GI_RUPEE_PURPLE_LOSE, // specific to chest minigame
    /* 0x76 */ GI_HEART_PIECE_WIN,   // specific to chest minigame
    /* 0x77 */ GI_STICK_UPGRADE_20,
    /* 0x78 */ GI_STICK_UPGRADE_30,
    /* 0x79 */ GI_NUT_UPGRADE_30,
    /* 0x7A */ GI_NUT_UPGRADE_40,
    /* 0x7B */ GI_BULLET_BAG_50,
    /* 0x7C */ GI_ICE_TRAP, // freezes link when opened from a chest
    /* 0x7D */ GI_TEXT_0,   // no model appears over Link, shows text id 0 (pocket egg)

    // The following values are custom items added by the randomizer

    /* 0x7E */ GI_SWORD_MASTER,

    /* 0x7F */ GI_7F, // unused

    /* 0x80 */ GI_PROG_HOOKSHOT,
    /* 0x81 */ GI_PROG_STRENGTH,
    /* 0x82 */ GI_PROG_BOMB_BAG,
    /* 0x83 */ GI_PROG_BOW,
    /* 0x84 */ GI_PROG_SLINGSHOT,
    /* 0x85 */ GI_PROG_WALLET,
    /* 0x86 */ GI_PROG_SCALE,
    /* 0x87 */ GI_PROG_NUT_UPGRADE,
    /* 0x88 */ GI_PROG_STICK_UPGRADE,
    /* 0x89 */ GI_PROG_BOMBCHUS,
    /* 0x8A */ GI_PROG_MAGIC_METER,
    /* 0x8B */ GI_PROG_OCARINA,

    /* 0x8C */ GI_BOTTLE_RED_POTION,
    /* 0x8D */ GI_BOTTLE_GREEN_POTION,
    /* 0x8E */ GI_BOTTLE_BLUE_POTION,
    /* 0x8F */ GI_BOTTLE_FAIRY,
    /* 0x90 */ GI_BOTTLE_FISH,
    /* 0x91 */ GI_BOTTLE_BLUE_FIRE,
    /* 0x92 */ GI_BOTTLE_BUGS,
    /* 0x93 */ GI_BOTTLE_BIG_POE,
    /* 0x94 */ GI_BOTTLE_POE,

    /* 0x95 */ GI_FOREST_BOSS_KEY,
    /* 0x96 */ GI_FIRE_BOSS_KEY,
    /* 0x97 */ GI_WATER_BOSS_KEY,
    /* 0x98 */ GI_SPIRIT_BOSS_KEY,
    /* 0x99 */ GI_SHADOW_BOSS_KEY,
    /* 0x9A */ GI_GANON_BOSS_KEY,

    /* 0x9B */ GI_DEKU_COMPASS,
    /* 0x9C */ GI_DODONGO_COMPASS,
    /* 0x9D */ GI_JABU_COMPASS,
    /* 0x9E */ GI_FOREST_COMPASS,
    /* 0x9F */ GI_FIRE_COMPASS,
    /* 0xA0 */ GI_WATER_COMPASS,
    /* 0xA1 */ GI_SPIRIT_COMPASS,
    /* 0xA2 */ GI_SHADOW_COMPASS,
    /* 0xA3 */ GI_BOTW_COMPASS,
    /* 0xA4 */ GI_ICE_CAVERN_COMPASS,

    /* 0xA5 */ GI_DEKU_MAP,
    /* 0xA6 */ GI_DODONGO_MAP,
    /* 0xA7 */ GI_JABU_MAP,
    /* 0xA8 */ GI_FOREST_MAP,
    /* 0xA9 */ GI_FIRE_MAP,
    /* 0xAA */ GI_WATER_MAP,
    /* 0xAB */ GI_SPIRIT_MAP,
    /* 0xAC */ GI_SHADOW_MAP,
    /* 0xAD */ GI_BOTW_MAP,
    /* 0xAE */ GI_ICE_CAVERN_MAP,

    /* 0xAF */ GI_FOREST_SMALL_KEY,
    /* 0xB0 */ GI_FIRE_SMALL_KEY,
    /* 0xB1 */ GI_WATER_SMALL_KEY,
    /* 0xB2 */ GI_SPIRIT_SMALL_KEY,
    /* 0xB3 */ GI_SHADOW_SMALL_KEY,
    /* 0xB4 */ GI_BOTW_SMALL_KEY,
    /* 0xB5 */ GI_GTG_SMALL_KEY,
    /* 0xB6 */ GI_FORTRESS_SMALL_KEY,
    /* 0xB7 */ GI_GANON_SMALL_KEY,

    /* 0xB8 */ GI_DOUBLE_DEFENSE,
    /* 0xB9 */ GI_MAGIC_METER,
    /* 0xBA */ GI_DOUBLE_MAGIC,

    /* 0xBB */ GI_MINUET,
    /* 0xBC */ GI_BOLERO,
    /* 0xBD */ GI_SERENADE,
    /* 0xBE */ GI_REQUIEM,
    /* 0xBF */ GI_NOCTURNE,
    /* 0xC0 */ GI_PRELUDE,
    /* 0xC1 */ GI_ZELDA_LULLABY,
    /* 0xC2 */ GI_EPONA_SONG,
    /* 0xC3 */ GI_SARIA_SONG,
    /* 0xC4 */ GI_SUN_SONG,
    /* 0xC5 */ GI_SONG_OF_TIME,
    /* 0xC6 */ GI_SONG_OF_STORMS,

    /* 0xC7 */ GI_TYCOON_WALLET,
    /* 0xC8 */ GI_LETTER_RUTO_2,
    /* 0xC9 */ GI_MAGIC_BEAN_PACK,
    /* 0xCA */ GI_TRIFORCE_PIECE,

    /* 0xCB */ GI_KOKIRI_EMERALD,
    /* 0xCC */ GI_GORON_RUBY,
    /* 0xCD */ GI_ZORA_SAPPHIRE,

    /* 0xCE */ GI_FOREST_MEDALLION,
    /* 0xCF */ GI_FIRE_MEDALLION,
    /* 0xD0 */ GI_WATER_MEDALLION,
    /* 0xD1 */ GI_SPIRIT_MEDALLION,
    /* 0xD2 */ GI_SHADOW_MEDALLION,
    /* 0xD3 */ GI_LIGHT_MEDALLION,

    /* 0xD4 */ GI_PROG_GORON_SWORD,

    /* 0xD5 */ GI_FOREST_KEY_RING,
    /* 0xD6 */ GI_FIRE_KEY_RING,
    /* 0xD7 */ GI_WATER_KEY_RING,
    /* 0xD8 */ GI_SPIRIT_KEY_RING,
    /* 0xD9 */ GI_SHADOW_KEY_RING,
    /* 0xDA */ GI_BOTW_KEY_RING,
    /* 0xDB */ GI_GTG_KEY_RING,
    /* 0xDC */ GI_FORTRESS_KEY_RING,
    /* 0xDD */ GI_GANON_KEY_RING,
    /* 0xDE */ GI_CHEST_GAME_KEY,

    /* 0xDF  */ GI_SOUL_POE,
    /* 0xE0  */ GI_SOUL_OCTOROK,
    /* 0xE1  */ GI_SOUL_KEESE,
    /* 0xE2  */ GI_SOUL_TEKTITE,
    /* 0xE3  */ GI_SOUL_LEEVER,
    /* 0xE4  */ GI_SOUL_PEAHAT,
    /* 0xE5  */ GI_SOUL_LIZALFOS,
    /* 0xE6  */ GI_SOUL_SHABOM,
    /* 0xE7  */ GI_SOUL_BIRI_BARI,
    /* 0xE8  */ GI_SOUL_TAILPASARAN,
    /* 0xE9  */ GI_SOUL_SKULLTULA,
    /* 0xEA  */ GI_SOUL_TORCH_SLUG,
    /* 0xEB  */ GI_SOUL_STINGER,
    /* 0xEC  */ GI_SOUL_MOBLIN,
    /* 0xED  */ GI_SOUL_ARMOS,
    /* 0xEE  */ GI_SOUL_DEKU_BABA,
    /* 0xEF  */ GI_SOUL_BUBBLE,
    /* 0xF0  */ GI_SOUL_FLYING_TRAP,
    /* 0xF1  */ GI_SOUL_BEAMOS,
    /* 0xF2  */ GI_SOUL_WALLMASTER,
    /* 0xF3  */ GI_SOUL_REDEAD_GIBDO,
    /* 0xF4  */ GI_SOUL_SHELL_BLADE,
    /* 0xF5  */ GI_SOUL_LIKE_LIKE,
    /* 0xF6  */ GI_SOUL_TENTACLE,
    /* 0xF7  */ GI_SOUL_ANUBIS,
    /* 0xF8  */ GI_SOUL_SPIKE,
    /* 0xF9  */ GI_SOUL_SKULL_KID,
    /* 0xFA  */ GI_SOUL_FREEZARD,
    /* 0xFB  */ GI_SOUL_DEKU_SCRUB,
    /* 0xFC  */ GI_SOUL_WOLFOS,
    /* 0xFD  */ GI_SOUL_STALCHILD,
    /* 0xFE  */ GI_SOUL_GUAY,
    /* 0xFF  */ GI_SOUL_DOOR_MIMIC,
    /* 0x100 */ GI_SOUL_STALFOS,
    /* 0x101 */ GI_SOUL_DARK_LINK,
    /* 0x102 */ GI_SOUL_FLARE_DANCER,
    /* 0x103 */ GI_SOUL_DEAD_HAND,
    /* 0x104 */ GI_SOUL_GERUDO,
    /* 0x105 */ GI_SOUL_GOHMA,
    /* 0x106 */ GI_SOUL_DODONGO,
    /* 0x107 */ GI_SOUL_BARINADE,
    /* 0x108 */ GI_SOUL_PHANTOM_GANON,
    /* 0x109 */ GI_SOUL_VOLVAGIA,
    /* 0x10A */ GI_SOUL_MORPHA,
    /* 0x10B */ GI_SOUL_BONGO_BONGO,
    /* 0x10C */ GI_SOUL_TWINROVA,
    /* 0x10D */ GI_SOUL_GANON,

    /* 0x10E */ GI_OCARINA_BUTTON_L,
    /* 0x10F */ GI_OCARINA_BUTTON_R,
    /* 0x110 */ GI_OCARINA_BUTTON_X,
    /* 0x111 */ GI_OCARINA_BUTTON_Y,
    /* 0x112 */ GI_OCARINA_BUTTON_A,

    /* 0x113 */ GI_RUPOOR,
} GetItemID;

typedef enum {
    DUNGEON_DEKU_TREE = 0,
    DUNGEON_DODONGOS_CAVERN,
    DUNGEON_JABUJABUS_BELLY,
    DUNGEON_FOREST_TEMPLE,
    DUNGEON_FIRE_TEMPLE,
    DUNGEON_WATER_TEMPLE,
    DUNGEON_SPIRIT_TEMPLE,
    DUNGEON_SHADOW_TEMPLE,
    DUNGEON_BOTTOM_OF_THE_WELL,
    DUNGEON_ICE_CAVERN,
    DUNGEON_GANONS_TOWER,
    DUNGEON_GERUDO_TRAINING_GROUNDS,
    DUNGEON_THIEVES_HIDEOUT,
    DUNGEON_INSIDE_GANONS_CASTLE,
    DUNGEON_GANONS_TOWER_COLLAPSING_INTERIOR,
    DUNGEON_GANONS_CASTLE_COLLAPSING,
    DUNGEON_TREASURE_CHEST_SHOP,
    DUNGEON_DEKU_TREE_BOSS_ROOM,
    DUNGEON_DODONGOS_CAVERN_BOSS_ROOM,
    DUNGEON_JABUJABUS_BELLY_BOSS_ROOM,
    DUNGEON_FOREST_TEMPLE_BOSS_ROOM,
    DUNGEON_FIRE_TEMPLE_BOSS_ROOM,
    DUNGEON_WATER_TEMPLE_BOSS_ROOM,
    DUNGEON_SPIRIT_TEMPLE_BOSS_ROOM,
    DUNGEON_SHADOW_TEMPLE_BOSS_ROOM,
} DungeonId;